cluster:
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    - /home/des/Talos/Talos/calico/tigera-operator.yaml
    - /home/des/Talos/Talos/calico/custom-resources.yaml 
    - /home/des/Talos/Talos/metallb/no-speakers-metallb-native.yaml
    - /home/des/Talos/Talos/metallb/ipaddress_pools.yaml
    - /home/des/Talos/Talos/metallb/l2advertisement.yaml
  controlPlane:
    endpoint: https://192.168.130.60:6443 
  network:
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
    cni:
      name: none
machine:
  network:
    interfaces:
    - interface: eth0
      vip:
        ip: 192.168.130.60
  kubelet:
    extraArgs:
      rotate-server-certificates: true
