---
- name: Check that the config file doesn't already exist
  ansible.builtin.stat:
    path: "{{ config_file }}"
  register: stat_result

# Generate Machine Configurations. 
- name: Generate config for cluster
  when: "not stat_result.stat.exists"
# use below for latest ----- generated online via image factory
# separate "PATCH"  files for control planes & worker nodes
  ansible.builtin.command: talosctl gen config {{ cluster_name }} https://{{ control_plane_ip }}:6443 --output-dir {{ config_directory }}  --install-image {{ talos_version }} --config-patch-control-plane @cp.yaml --config-patch-worker @worker.yaml
  changed_when: true
